// <auto-generated />
namespace KateFordLedger.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class bankAccount : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(bankAccount));
        
        string IMigrationMetadata.Id
        {
            get { return "201808162055572_bankAccount"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
